version: '3'
services:
  drawio:
    build:
      context: ..
      dockerfile: alpine/Dockerfile
    image: jknight-drawio:latest
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443