version: '3'
services:
  drawio:
    build:
      context: ..
      dockerfile: alpine/Dockerfile
    image: jknight-drawio:latest
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
  drawio-nginx:
    image: registry.gitlab.com/immediation/docker/drawio-nginx:latest
    container_name: drawio-nginx
    restart: unless-stopped
    ports:
      - 8001:80
  